// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXRziaXWuSZpmQNLWZ0Z09qYT9cQeNPi0',
    appId: '1:399590041523:web:5fcdb5fb71201045454dc6',
    messagingSenderId: '399590041523',
    projectId: 'crudfirebase-a66f6',
    authDomain: 'crudfirebase-a66f6.firebaseapp.com',
    storageBucket: 'crudfirebase-a66f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZBANC-eUkMW_A4HZPzZOrkUiFUGiIK-c',
    appId: '1:399590041523:android:0e540329177f7dbb454dc6',
    messagingSenderId: '399590041523',
    projectId: 'crudfirebase-a66f6',
    storageBucket: 'crudfirebase-a66f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtOAwDGDYU7QPZYB0UeLaqs_WZqUUv09M',
    appId: '1:399590041523:ios:f98e6589b23404d0454dc6',
    messagingSenderId: '399590041523',
    projectId: 'crudfirebase-a66f6',
    storageBucket: 'crudfirebase-a66f6.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtOAwDGDYU7QPZYB0UeLaqs_WZqUUv09M',
    appId: '1:399590041523:ios:e8ebe5c0a4e6455b454dc6',
    messagingSenderId: '399590041523',
    projectId: 'crudfirebase-a66f6',
    storageBucket: 'crudfirebase-a66f6.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseDatabase.RunnerTests',
  );
}
